document_processor:
  type: "default"

  chunker:
    type: "recursive"
    chunk_size: 512
    chunk_overlap: 65

  loaders:
    - "html"
    - "pdf"
    - "docx"
    - "markdown"
    - "epub"
    - "text"
    - "xaml"

  documents_store:
    type: "postgres"

retriever:
  type: "dense"
  filter_oversample_factor: 4

  vector_storage:
    type: "faiss"

  embedder:
    type: "sentence_transformer"
    name: "BAAI/bge-m3"
    device: "cuda"
